const data = [
  {
    id: 1,
    edition: 'USA 2018',
    name: 'Thunderbolt',
    type: 'action',
    src: './Images/img.png',
  },
  {
    id: 2,
    edition: 'USA 2018',
    name: 'Thunderbolt',
    type: 'action',
    src: './Images/img.png',
  },
  {
    id: 3,
    edition: 'USA 2018',
    name: 'Thunderbolt',
    type: 'action',
    src: './Images/img.png',
  },
  {
    id: 4,
    edition: 'USA 2018',
    name: 'Thunderbolt',
    type: 'action',
    src: './Images/img.png',
  },
  {
    id: 5,
    edition: 'USA 2018',
    name: 'Thunderbolt',
    type: 'action',
    src: './Images/img.png',
  },
  {
    id: 6,
    edition: 'USA 2018',
    name: 'Thunderbolt',
    type: 'action',
    src: './Images/img.png',
  },
  {
    id: 7,
    edition: 'USA 2018',
    name: 'Thunderbolt',
    type: 'action',
    src: './Images/img.png',
  },
  {
    id: 8,
    edition: 'USA 2018',
    name: 'Thunderbolt',
    type: 'action',
    src: './Images/img.png',
  },
  {
    id: 9,
    edition: 'USA 2018',
    name: 'Thunderbolt',
    type: 'action',
    src: './Images/img.png',
  },
  {
    id: 10,
    edition: 'USA 2018',
    name: 'Thunderbolt',
    type: 'action',
    src: './Images/img.png',
  },
  {
    id: 11,
    edition: 'USA 2018',
    name: 'Thunderbolt',
    type: 'action',
    src: './Images/img.png',
  },
]

export default data
